export const COUNTRIES: { [key: string]: { name: string, capital: string } }[] = [
    { "Afghanistan": { "name": "Ауғанстан", "capital": "Кабул" } },
    { "Albania": { "name": "Албания", "capital": "Тирана" } },
    { "Algeria": { "name": "Алжир", "capital": "Алжир" } },
    { "Andorra": { "name": "Андорра", "capital": "Андорра-ла-Велья" } },
    { "Angola": { "name": "Ангола", "capital": "Луанда" } },
    { "Antigua and Barbuda": { "name": "Антигуа және Барбуда", "capital": "Сент-Джонс" } },
    { "Argentina": { "name": "Аргентина", "capital": "Буэнос-Айрес" } },
    { "Armenia": { "name": "Армения", "capital": "Ереван" } },
    { "Australia": { "name": "Австралия", "capital": "Канберра" } },
    { "Austria": { "name": "Австрия", "capital": "Вена" } },
    { "Azerbaijan": { "name": "Әзірбайжан", "capital": "Баку" } },
    { "Bahamas": { "name": "Багамы", "capital": "Нассау" } },
    { "Bahrain": { "name": "Бахрейн", "capital": "Манама" } },
    { "Bangladesh": { "name": "Бангладеш", "capital": "Дакка" } },
    { "Barbados": { "name": "Барбадос", "capital": "Бриджтаун" } },
    { "Belarus": { "name": "Беларусь", "capital": "Минск" } },
    { "Belgium": { "name": "Бельгия", "capital": "Брюссель" } },
    { "Belize": { "name": "Белиз", "capital": "Бельмопан" } },
    { "Benin": { "name": "Бенин", "capital": "Порто-Ново" } },
    { "Bhutan": { "name": "Бутан", "capital": "Тхимпху" } },
    { "Bolivia": { "name": "Боливия", "capital": "Сукре" } },
    { "Bosnia and Herzegovina": { "name": "Босния және Герцеговина", "capital": "Сараево" } },
    { "Botswana": { "name": "Ботсвана", "capital": "Габороне" } },
    { "Brazil": { "name": "Бразилия", "capital": "Бразилиа" } },
    { "Brunei": { "name": "Бруней", "capital": "Бандар-Сери-Бегаван" } },
    { "Bulgaria": { "name": "Болгария", "capital": "София" } },
    { "Burkina Faso": { "name": "Буркина-Фасо", "capital": "Уагадугу" } },
    { "Burundi": { "name": "Бурунди", "capital": "Бужумбура" } },
    { "Cabo Verde": { "name": "Кабо-Верде", "capital": "Прая" } },
    { "Cambodia": { "name": "Камбоджа", "capital": "Пномпень" } },
    { "Cameroon": { "name": "Камерун", "capital": "Яунде" } },
    { "Canada": { "name": "Канада", "capital": "Оттава" } },
    { "Central African Republic": { "name": "Орталық Африка Республикасы", "capital": "Банги" } },
    { "Chad": { "name": "Чад", "capital": "Нджамена" } },
    { "Chile": { "name": "Чили", "capital": "Сантьяго" } },
    { "China": { "name": "Қытай", "capital": "Бейжің" } },
    { "Colombia": { "name": "Колумбия", "capital": "Богота" } },
    { "Comoros": { "name": "Коморлар", "capital": "Морони" } },
    { "Congo (Congo-Brazzaville)": { "name": "Конго (Браззавиль)", "capital": "Браззавиль" } },
    { "Congo (Democratic Republic of the Congo)": { "name": "Конго (Демократиялық Республика)", "capital": "Киншаса" } },
    { "Costa Rica": { "name": "Коста-Рика", "capital": "Сан-Хосе" } },
    { "Croatia": { "name": "Хорватия", "capital": "Загреб" } },
    { "Cuba": { "name": "Куба", "capital": "Гавана" } },
    { "Cyprus": { "name": "Кипр", "capital": "Никосия" } },
    { "Czech Republic": { "name": "Чехия", "capital": "Прага" } },
    { "Denmark": { "name": "Дания", "capital": "Копенгаген" } },
    { "Djibouti": { "name": "Джибути", "capital": "Джибути" } },
    { "Dominica": { "name": "Доминика", "capital": "Розо" } },
    { "Dominican Republic": { "name": "Доминикан Республикасы", "capital": "Санта-Доминика" } },
    { "Ecuador": { "name": "Эквадор", "capital": "Кито" } },
    { "Egypt": { "name": "Египет", "capital": "Каир" } },
    { "El Salvador": { "name": "Сальвадор", "capital": "Сан-Сальвадор" } },
    { "Equatorial Guinea": { "name": "Экваторлық Гвинея", "capital": "Малабо" } },
    { "Eritrea": { "name": "Эритрея", "capital": "Асмара" } },
    { "Estonia": { "name": "Эстония", "capital": "Таллинн" } },
    { "Eswatini": { "name": "Эсватини", "capital": "Мбабане" } },
    { "Ethiopia": { "name": "Эфиопия", "capital": "Аддис-Абеба" } },
    { "Fiji": { "name": "Фиджи", "capital": "Суве" } },
    { "Finland": { "name": "Финляндия", "capital": "Хельсинки" } },
    { "France": { "name": "Франция", "capital": "Париж" } },
    { "Gabon": { "name": "Габон", "capital": "Либревиль" } },
    { "Gambia": { "name": "Гамбия", "capital": "Банжул" } },
    { "Georgia": { "name": "Грузия", "capital": "Тбилиси" } },
    { "Germany": { "name": "Германия", "capital": "Берлин" } },
    { "Ghana": { "name": "Гана", "capital": "Аккра" } },
    { "Greece": { "name": "Греция", "capital": "Афины" } },
    { "Grenada": { "name": "Гренада", "capital": "Сент-Джорджес" } },
    { "Guatemala": { "name": "Гватемала", "capital": "Гватемала-Сити" } },
    { "Guinea": { "name": "Гвинея", "capital": "Конакри" } },
    { "Guinea-Bissau": { "name": "Гвинея-Бисау", "capital": "Бисау" } },
    { "Guyana": { "name": "Гайана", "capital": "Джорджтаун" } },
    { "Haiti": { "name": "Гаити", "capital": "Порт-о-Пренс" } },
    { "Honduras": { "name": "Гондурас", "capital": "Тегусигальпа" } },
    { "Hungary": { "name": "Венгрия", "capital": "Будапешт" } },
    { "Iceland": { "name": "Исландия", "capital": "Рейкьявик" } },
    { "India": { "name": "Үндістан", "capital": "Нью-Дели" } },
    { "Indonesia": { "name": "Индонезия", "capital": "Джакарта" } },
    { "Iran": { "name": "Иран", "capital": "Тегеран" } },
    { "Iraq": { "name": "Ирак", "capital": "Багдад" } },
    { "Ireland": { "name": "Ирландия", "capital": "Дублин" } },
    { "Israel": { "name": "Израиль", "capital": "Иерусалим" } },
    { "Italy": { "name": "Италия", "capital": "Рим" } },
    { "Jamaica": { "name": "Ямайка", "capital": "Кингстон" } },
    { "Japan": { "name": "Жапония", "capital": "Токио" } },
    { "Jordan": { "name": "Иордания", "capital": "Амман" } },
    { "Kazakhstan": { "name": "Қазақстан", "capital": "Астана" } },
    { "Kenya": { "name": "Кения", "capital": "Найроби" } },
    { "Kiribati": { "name": "Кирибати", "capital": "Тарава" } },
    { "Korea, North": { "name": "Солтүстік Корея", "capital": "Пхеньян" } },
    { "Korea, South": { "name": "Оңтүстік Корея", "capital": "Сеул" } },
    { "Kuwait": { "name": "Кувейт", "capital": "Кувейт-Сити" } },
    { "Kyrgyzstan": { "name": "Қырғызстан", "capital": "Бішкек" } },
    { "Laos": { "name": "Лаос", "capital": "Вьентьян" } },
    { "Latvia": { "name": "Латвия", "capital": "Рига" } },
    { "Lebanon": { "name": "Ливан", "capital": "Бейрут" } },
    { "Lesotho": { "name": "Лесото", "capital": "Масеру" } },
    { "Liberia": { "name": "Либерия", "capital": "Монровия" } },
    { "Libya": { "name": "Ливия", "capital": "Триполи" } },
    { "Liechtenstein": { "name": "Лихтенштейн", "capital": "Вадуц" } },
    { "Lithuania": { "name": "Литва", "capital": "Вильнюс" } },
    { "Luxembourg": { "name": "Люксембург", "capital": "Люксембург" } },
    { "Madagascar": { "name": "Мадагаскар", "capital": "Антананариву" } },
    { "Malawi": { "name": "Малави", "capital": "Лилонгве" } },
    { "Malaysia": { "name": "Малайзия", "capital": "Куала-Лумпур" } },
    { "Maldives": { "name": "Мальдивы", "capital": "Мале" } },
    { "Mali": { "name": "Мали", "capital": "Бамако" } },
    { "Malta": { "name": "Мальта", "capital": "Валлетта" } },
    { "Marshall Islands": { "name": "Маршалловы Острова", "capital": "Маджуро" } },
    { "Mauritania": { "name": "Мавритания", "capital": "Ноуакшот" } },
    { "Mauritius": { "name": "Маврикий", "capital": "Порт-Луи" } },
    { "Mexico": { "name": "Мексика", "capital": "Мехико" } },
    { "Micronesia": { "name": "Федеративные Штаты Микронезии", "capital": "Паликир" } },
    { "Moldova": { "name": "Молдова", "capital": "Кишинев" } },
    { "Monaco": { "name": "Монако", "capital": "Монако" } },
    { "Mongolia": { "name": "Моңғолия", "capital": "Улан-Батор" } },
    { "Montenegro": { "name": "Черногория", "capital": "Подгорица" } },
    { "Morocco": { "name": "Марокко", "capital": "Рабат" } },
    { "Mozambique": { "name": "Мозамбик", "capital": "Мапуту" } },
    { "Myanmar": { "name": "Мьянма", "capital": "Нейпьидо" } },
    { "Namibia": { "name": "Намибия", "capital": "Виндхук" } },
    { "Nauru": { "name": "Науру", "capital": "Ярен" } },
    { "Nepal": { "name": "Непал", "capital": "Катманду" } },
    { "Netherlands": { "name": "Нидерланды", "capital": "Амстердам" } },
    { "New Zealand": { "name": "Жаңа Зеландия", "capital": "Уеллингтон" } },
    { "Nicaragua": { "name": "Никарагуа", "capital": "Манагуа" } },
    { "Niger": { "name": "Нигер", "capital": "Ниамей" } },
    { "Nigeria": { "name": "Нигерия", "capital": "Абуджа" } },
    { "North Macedonia": { "name": "Северная Македония", "capital": "Скопье" } },
    { "Norway": { "name": "Норвегия", "capital": "Осло" } },
    { "Oman": { "name": "Оман", "capital": "Маскат" } },
    { "Pakistan": { "name": "Пәкістан", "capital": "Исламабад" } },
    { "Palau": { "name": "Палау", "capital": "Нгерулмуд" } },
    { "Panama": { "name": "Панама", "capital": "Панама" } },
    { "Papua New Guinea": { "name": "Папуа - Жаңа Гвинея", "capital": "Порт-Морсби" } },
    { "Paraguay": { "name": "Парагвай", "capital": "Асунсьон" } },
    { "Peru": { "name": "Перу", "capital": "Лима" } },
    { "Philippines": { "name": "Филиппины", "capital": "Манила" } },
    { "Poland": { "name": "Польша", "capital": "Варшава" } },
    { "Portugal": { "name": "Португалия", "capital": "Лиссабон" } },
    { "Qatar": { "name": "Қатар", "capital": "Доха" } },
    { "Romania": { "name": "Румыния", "capital": "Бухарест" } },
    { "Russia": { "name": "Ресей", "capital": "Мәскеу" } },
    { "Rwanda": { "name": "Руанда", "capital": "Кигали" } },
    { "Saint Kitts and Nevis": { "name": "Сент-Китс және Невис", "capital": "Бастер" } },
    { "Saint Lucia": { "name": "Сент-Люсия", "capital": "Кастри" } },
    { "Saint Vincent and the Grenadines": { "name": "Сент-Винсент және Гренадины", "capital": "Кингстаун" } },
    { "Samoa": { "name": "Самоа", "capital": "Апиа" } },
    { "San Marino": { "name": "Сан-Марино", "capital": "Сан-Марино" } },
    { "Sao Tome and Principe": { "name": "Сан-Томе және Принсипи", "capital": "Сан-Томе" } },
    { "Saudi Arabia": { "name": "Сауд Арабиясы", "capital": "Эр-Рияд" } },
    { "Senegal": { "name": "Сенегал", "capital": "Дакар" } },
    { "Serbia": { "name": "Сербия", "capital": "Белград" } },
    { "Seychelles": { "name": "Сейшельские Острова", "capital": "Виктория" } },
    { "Sierra Leone": { "name": "Сьерра-Леоне", "capital": "Фритаун" } },
    { "Singapore": { "name": "Сингапур", "capital": "Сингапур" } },
    { "Slovakia": { "name": "Словакия", "capital": "Братислава" } },
    { "Slovenia": { "name": "Словения", "capital": "Любляна" } },
    { "Solomon Islands": { "name": "Соломоновы Острова", "capital": "Хониара" } },
    { "Somalia": { "name": "Сомали", "capital": "Могадишо" } },
    { "South Africa": { "name": "Оңтүстік Африка", "capital": "Претория" } },
    { "South Sudan": { "name": "Оңтүстік Судан", "capital": "Джуба" } },
    { "Spain": { "name": "Испания", "capital": "Мадрид" } },
    { "Sri Lanka": { "name": "Шри-Ланка", "capital": "Коломбо" } },
    { "Sudan": { "name": "Судан", "capital": "Хартум" } },
    { "Suriname": { "name": "Суринам", "capital": "Парамарибо" } },
    { "Sweden": { "name": "Швеция", "capital": "Стокгольм" } },
    { "Switzerland": { "name": "Швейцария", "capital": "Берн" } },
    { "Syria": { "name": "Сирия", "capital": "Дамаск" } },
    { "Taiwan": { "name": "Тайвань", "capital": "Тайбэй" } },
    { "Tajikistan": { "name": "Тәжікстан", "capital": "Душанбе" } },
    { "Tanzania": { "name": "Танзания", "capital": "Додома" } },
    { "Thailand": { "name": "Тайланд", "capital": "Бангкок" } },
    { "Timor-Leste": { "name": "Шығыс Тимор", "capital": "Дили" } },
    { "Togo": { "name": "Того", "capital": "Ломе" } },
    { "Tonga": { "name": "Тонга", "capital": "Нукуалофа" } },
    { "Trinidad and Tobago": { "name": "Тринидад және Тобаго", "capital": "Порт-оф-Спейн" } },
    { "Tunisia": { "name": "Тунис", "capital": "Тунис" } },
    { "Turkey": { "name": "Түркия", "capital": "Анкара" } },
    { "Turkmenistan": { "name": "Түркменстан", "capital": "Ашхабад" } },
    { "Tuvalu": { "name": "Тувалу", "capital": "Фунафути" } },
    { "Uganda": { "name": "Уганда", "capital": "Кампала" } },
    { "Ukraine": { "name": "Украина", "capital": "Киев" } },
    { "United Arab Emirates": { "name": "Біріккен Араб Әмірліктері", "capital": "Абу-Даби" } },
    { "United Kingdom": { "name": "Ұлыбритания", "capital": "Лондон" } },
    { "United States": { "name": "АҚШ", "capital": "Вашингтон" } },
    { "Uruguay": { "name": "Уругвай", "capital": "Монтевидео" } },
    { "Uzbekistan": { "name": "Өзбекстан", "capital": "Ташкент" } },
    { "Vanuatu": { "name": "Вануату", "capital": "Порт-Вила" } },
    { "Vatican City": { "name": "Ватикан", "capital": "Ватикан" } },
    { "Venezuela": { "name": "Венесуэла", "capital": "Каракас" } },
    { "Vietnam": { "name": "Вьетнам", "capital": "Ханой" } },
    { "Yemen": { "name": "Йемен", "capital": "Санаа" } },
    { "Zambia": { "name": "Замбия", "capital": "Лусака" } },
    { "Zimbabwe": { "name": "Зимбабве", "capital": "Хараре" } }
];